version: '2.4'

services:
  spark:
    build: .
    stdin_open: true
    tty: true
    mem_limit: 8g
    volumes:
      - "$LIBS_FOLDER:/libs"
      - "$CONF_FOLDER:/conf"

    environment:
      - "LOG4J_FILENAME=log4j.xml"
    command: ["$EXE_FILE", "$MAIN_CLASS"]